### ISSUE TITLE
OSH Park gives Warning (non-critical)

### ISSUE THREAD

**Issue by paalfe** [arithmaldor/Phoenix-Adapter#1]
I uploaded gerbers-zip-files to oshpark.com and they give a Warning (non-critical): 
Detected unsupported drilled slots. 

----------

![screenshot from 2018-05-31 01-03-52](https://user-images.githubusercontent.com/388648/40752174-b41032ec-646e-11e8-89b1-629b4173fc99.png)

----------

![screenshot from 2018-05-31 01-03-13](https://user-images.githubusercontent.com/388648/40752175-b4345262-646e-11e8-851a-8e7dda52dd78.png)

----------

Help page: http://docs.oshpark.com/troubleshooting/cutouts-and-slots/

**Slots using unsupported callouts**
The following common slot types fall into this category.
- `G85` Drill Drag callouts.
- `G00`+`G01` Excellon drill milling instructions.
- Drill files containing Gerber data to indicate slot information.

Our system will attempt to notify you if these slot types are detected. Closely examining the previews will help indicate if the slot matches an acceptable callout.

Most tools can convert these callouts to a supported method by simply drawing additional details on the board outline.

A typical slot indicated with a non-supported callout

![slot-plated-unsupported](https://user-images.githubusercontent.com/388648/40893045-4b9a44bc-679f-11e8-95a6-ea6587bffc6d.png)

----------

From the twitter post https://twitter.com/Arithmaldor/status/1000977450854121473?s=20 it should look more like this:

![2018-06-03 15_51_11-window](https://user-images.githubusercontent.com/388648/40887249-0a1dcca6-6746-11e8-9eec-6f1966635be8.png)

**Comment by paalfe** [comment]
From the twitter post https://twitter.com/Arithmaldor/status/1000977450854121473?s=20 the holes should more like this:

![2018-06-03 15_51_11-window](https://user-images.githubusercontent.com/388648/40887249-0a1dcca6-6746-11e8-9eec-6f1966635be8.png)

**Comment by arithmaldor** [comment]
Thanks for pointing this out! Apparently "slot" footprints don't translate properly in OSHPark. I am working on fixing this.

**Comment by arithmaldor** [comment]
This is now fixed in version 0.2. Plated slots are not officially supported by OSH Park, but following instructions here:
https://forum.kicad.info/t/oval-pads-not-possible-for-oshpark/835/4
It is possible to get around this. OSH Park will still give a warning, but the preview will look correct and it should be fabricated correctly.
![image](https://user-images.githubusercontent.com/38473301/41633506-45992f18-740d-11e8-9fb4-8cb22a8b2c5e.png)
